stages:
  - review

review:
  image: alpine
  before_script:
    - apk add --no-cache python3 git bash curl jq --quiet
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.korputeam.ru/newbackend/level85.git /tmp/level85
    - ln -sf /tmp/level85/AGENTS.md ${CI_PROJECT_DIR}/AGENTS.md
    # - ln -sf /tmp/level85/DOD.md ${CI_PROJECT_DIR}/DOD.md
    - ln -sf /tmp/level85/.agents ${CI_PROJECT_DIR}/.agents
  stage: review
  variables:
    GIT_DEPTH: 0
    ZAI_API_KEY: "077f7f72b2e9400984cd73a3a15eb205.20VNPwsHVRGJAcL4"
    REPORTER_API_TOKEN: "glpat-y37Zif3Z1ysx5dpuJjtq"
    # YAM_CHAT_ID: "1/0/a68cbd2f-b9b5-48cb-8b3d-5b75bcc119f3"
  script:
    - TEXT=$(/tmp/level85/scripts/get-diff.sh | python3 /tmp/level85/scripts/get-code-review.py)
    - NOTE=$(/tmp/level85/scripts/send-gitlab-report.sh "$TEXT")
    # - /tmp/level85/scripts/send-yam-mr.sh "$NOTE"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
      # when: never # ZAI_API_KEY протух, временно отключено
